### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by skreem** [OvercastNetwork/ProjectAres#1]
Will we be seeing the website open sourced as well?

**Comment by vYuri** [comment]
No

**Comment by EricZeiberg** [comment]
@vYuri How do you know?

**Comment by RubeVi** [comment]
@skreem they use [forem](https://github.com/rubysherpas/forem) but since the gem is a little deprecated, you can use [thredded](https://github.com/thredded/thredded)

**Comment by kblanks** [comment]
@RubeVi The site is a lot more than just forem.

**Comment by RubeVi** [comment]
@kblanks but if they don't share it you can start with forem

**Comment by kblanks** [comment]
We're just interested in the code since the last _"release"_ of OCN web, we know how to use forem.

**Comment by skreem** [comment]
@RubeVi Yes, but as @kblanks said the site has many more features that would be valuable to many as an open source project. 
Forem really isn't a concern, there's an old version of OCN's forem [here](https://github.com/kultus/forem-2)

And a similar forum system [here](https://github.com/NJayDevelopment/mongoid_forums)

**Comment by Pablete1234** [comment]
The Web may be open sourced at a latter date, it's not a priority now though. We wanted to OS PGM in a rush asap so others can start contributing to it and start making it more usable for standalone servers.

**Comment by skreem** [comment]
@Pablete1234 Sounds reasonable, thanks for the response.
