### ISSUE TITLE
While destroying a monument, the fireworks kill you

### ISSUE THREAD

**Issue by xuxxxxo** [OvercastNetwork/ProjectAres#12]
https://www.youtube.com/watch?v=PVv48KRrT3w&feature=youtu.be

When you destroy a monument in Fractal Descent (or other maps, i didn't try it) the fireworks of the monument can kill you

**Comment by iPolish** [comment]
It's the mine craft not the plugin
W dniu czw., 2.02.2017 o 23:40 Xu <notifications@github.com> napisał(a):

**Comment by Pablete1234** [comment]
@xuxxxxo You need to properly setup the `global.xml`
