### ISSUE TITLE
How to runed plugin!11!??

### ISSUE THREAD

**Issue by vladthegreat100** [OvercastNetwork/ProjectAres#2]
![help](https://cloud.githubusercontent.com/assets/7694475/22409736/d30164f0-e65c-11e6-9b92-b28ec458b4ff.png)
how to runed plugin!11!??

**Comment by CoWinkKeyDinkInc** [comment]
You need to compile it using Ellipse or something.  Just give it a while, they're trying to remove all the dependents to make it work for casual use.

**Comment by RubeVi** [comment]
I think cubist will make a guide, idk tbh

**Comment by TheMolkaPL** [comment]
You need to install Apache Maven and run `mvn clean install` in your command line.
