### ISSUE TITLE
Punishments don't work 

### ISSUE THREAD

**Issue by iPolish** [OvercastNetwork/ProjectAres#23]
https://hastebin.com/anigupuqeq.vbs
This happend when i warned a guy

**Comment by RainoBoy97** [comment]
`The following errors were found: Type is not included in the list, Playing time ms can't be blank`
Pretty self-explanatory error, you don't have any statistics recorded in the database for the user(s). You probably have to run the `player-stats` script (don't know how).

**Comment by iPolish** [comment]
I run it

**Comment by iPolish** [comment]
They have stats

**Comment by iPolish** [comment]
Runt by using load("player-stats.js")
