### ISSUE TITLE
Unable to load server from Sportbukkit file

### ISSUE THREAD

**Issue by jackbear9** [OvercastNetwork/ProjectAres#34]
I have downloaded all the required plugins and files listed under "Running". How do you start the server once acquiring all the files?

**Comment by kailan** [comment]
`java -jar SportBukkit.jar`

**Comment by jackbear9** [comment]
I have that step down but where does the rest of the files go after. Which go into Bungeecord modules/plugins and which go into plugins folder for sportbukkit?
