### ISSUE TITLE
API-OCN Failed to build

### ISSUE THREAD

**Issue by xEndarZzz** [OvercastNetwork/ProjectAres#38]
I got this error:

[INFO] Reactor Summary:
[INFO]
[INFO] ProjectAres 1.11-SNAPSHOT .......................... SUCCESS [  2.367 s]
[INFO] Util ............................................... SUCCESS [  0.000 s]
[INFO] util-core .......................................... SUCCESS [ 50.222 s]
[INFO] util-bukkit ........................................ SUCCESS [  8.639 s]
[INFO] util-bungee ........................................ SUCCESS [  2.085 s]
[INFO] API Parent ......................................... SUCCESS [  0.000 s]
[INFO] API ................................................ SUCCESS [ 25.542 s]
[INFO] API-Minecraft ...................................... SUCCESS [  4.876 s]
[INFO] API-OCN ............................................ FAILURE [  0.377 s]
[INFO] API-Bukkit ......................................... SKIPPED
[INFO] API-Bungee ......................................... SKIPPED
[INFO] commons ............................................ SKIPPED
[INFO] commons-core ....................................... SKIPPED
[INFO] commons-bukkit ..................................... SKIPPED
[INFO] commons-bungee ..................................... SKIPPED
[INFO] PGM ................................................ SKIPPED
[INFO] Lobby .............................................. SKIPPED
[INFO] Tourney 1.11-SNAPSHOT .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2018-06-20T14:42:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.0:revision (default) on project api-ocn: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api-ocn

Please leave a comment if you know how to fix this error!

**Comment by xEndarZzz** [comment]
If you can, please give me the 2 .jar file in the target file instead!

**Comment by kailan** [comment]
@xEndarZzz Did you clone the repository using git or did you download a .zip from GitHub?

**Comment by xEndarZzz** [comment]
@kailan I download the .zip from github and I extract it. After I extract it, i opened the ProjectAres-master folder and open a "Git Bash Here" and type "mvn clean package" (I already downloaded maven)

**Comment by xEndarZzz** [comment]
@kailan can you just give me that jar file and I can skipped that task?

**Comment by xEndarZzz** [comment]
I looked at the pom.xml on api-ocn folder, i found that the repository is missing

**Comment by xEndarZzz** [comment]
Sorry for annoying you, it is inportant!

**Comment by kailan** [comment]
The project requires the Git repository metadata to compile successfully, and this isn't included in the archive that you downloaded.

Delete the ProjectAres folder from your computer and run `git clone https://github.com/OvercastNetwork/ProjectAres` in Git Bash to download the repository (including the Git data required). Compiling should then work 👌

**Comment by xEndarZzz** [comment]
@kailan thanks for the help! Much appreciated!

**Comment by jasoryeh** [comment]
Or, if you happen to know maven, you could remove the plugin that uses that data.

**Comment by Pablete1234** [comment]
I'm closing this as it seems to be resolved
